### ISSUE TITLE
Update docs to reflect Thing Plus ESP32-C6 board library availability

### ISSUE THREAD

**Issue by faludi** [sparkfun/SparkFun_Thing_Plus_ESP32_C6#1]
The documentation in docs/software_setup.md should be updated to reflect that the Thing Plus ESP32-C6 is now included in the official ESP32 boards package, and that using the ESP32C6 Dev Module board definition is no longer required.

**Comment by SFEMark** [comment]
The software_setup.md file and the relevant screenshots have been updated to the v3.x release of the ESP32 boards package.
